# Generated by Django 2.0.7 on 2018-10-27 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_reg', '0002_labreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.BigIntegerField()),
                ('description', models.CharField(default='', max_length=20)),
                ('complaint_date', models.DateField(default=datetime.date.today)),
                ('complaint_status', models.CharField(default='', max_length=10)),
                ('complaint_reply', models.CharField(default='', max_length=30)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reg.LabReg')),
            ],
        ),
    ]
