# Generated by Django 2.0.7 on 2018-11-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitrequest',
            old_name='login_id',
            new_name='members_name',
        ),
    ]
