# Generated by Django 2.0.7 on 2018-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_request', '0002_auto_20181125_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitrequest',
            name='members_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
