# Generated by Django 2.0.7 on 2018-10-22 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_reg', '0002_labreg'),
        ('chit', '0002_chit'),
        ('chit_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_details_date', models.DateField(default=datetime.date.today)),
                ('chit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('members_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reg.LabReg')),
            ],
        ),
    ]
