# Generated by Django 2.0.7 on 2018-11-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_details', '0004_auto_20181125_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitdetails',
            old_name='login_id',
            new_name='members_name',
        ),
    ]
