# Generated by Django 2.0.7 on 2018-10-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ]

    operations = [

    ]
