# Generated by Django 2.0.7 on 2018-10-22 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chit', '0002_chit'),
        ('chit_details', '0002_chitdetails'),
        ('chit_final_install', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitFinalInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_install_amount', models.BigIntegerField()),
                ('chit_imonth', models.DateField(default=datetime.date.today)),
                ('fchit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('fmember_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_details.ChitDetails')),
            ],
        ),
    ]
